<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Diagnostics" Condition="'$(Configuration)' == 'Debug'" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aphelion.Desktop.Application\Aphelion.Desktop.Application.csproj" />
    <ProjectReference Include="..\Aphelion.Desktop.BrowserEngine\Aphelion.Desktop.BrowserEngine.csproj" />
    <ProjectReference Include="..\Aphelion.Desktop.Domain\Aphelion.Desktop.Domain.csproj" />
    <ProjectReference Include="..\Aphelion.Desktop.Infrastructure\Aphelion.Desktop.Infrastructure.csproj" />
  </ItemGroup>

</Project>
